### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hkienle** [OpenElectronicsLab/level-shifter#1]
Can you please add a license?

**Comment by ace-dvm** [comment]
Oops, looks like we forgot that. Sorry! It's now been added.

**Comment by hkienle** [comment]
Great, thanks!

**Comment by ericherman** [comment]
As this was something we haven't touched in years, it was quite out of date. I updated the project to KiCAD 5.1, if you run into a problem please mention. If you plan to etch the PCB by hand, I'd enjoy learning of your results. Good luck and cheers! -Eric

**Comment by hkienle** [comment]
Thanks, very helpful!

BTW, if I understand correctly, this design "converts" 3.3V (or anything more than V_IH=2V) to 5V (=VCC) !?
